In [2]:
#Libraries
import pandas as pd

In [3]:
#load data from csv 
data = pd.read_csv ('diabetic_data1.csv')

In [4]:
#Show data frame details 
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
patient_nbr,101766.0,5.433040e+07,3.869636e+07,135.0,23413221.0,45505143.0,87545949.75,189502619.0
admission_type_id,101766.0,2.024006e+00,1.445403e+00,1.0,1.0,1.0,3.00,8.0
discharge_disposition_id,101766.0,3.715642e+00,5.280166e+00,1.0,1.0,1.0,4.00,28.0
admission_source_id,101766.0,5.754437e+00,4.064081e+00,1.0,1.0,7.0,7.00,25.0
time_in_hospital,101766.0,4.395987e+00,2.985108e+00,1.0,2.0,4.0,6.00,14.0
num_lab_procedures,101766.0,4.309564e+01,1.967436e+01,1.0,31.0,44.0,57.00,132.0
num_procedures,101766.0,1.339730e+00,1.705807e+00,0.0,0.0,1.0,2.00,6.0
num_medications,101766.0,1.602184e+01,8.127566e+00,1.0,10.0,15.0,20.00,81.0
number_outpatient,101766.0,3.693572e-01,1.267265e+00,0.0,0.0,0.0,0.00,42.0
number_emergency,101766.0,1.978362e-01,9.304723e-01,0.0,0.0,0.0,0.00,76.0
number_inpatient,101766.0,6.355659e-01,1.262863e+00,0.0,0.0,0.0,1.00,21.0
number_diagnoses,101766.0,7.422607e+00,1.933600e+00,1.0,6.0,8.0,9.00,16.0

In [48]:
#Drop encounter_ID

In [70]:
#clean whole data frame from ?s
data=data.replace ('?','')
data=data.replace (' ','')

In [71]:
#Drop all nominal values and then run correlation statistics
#replace nominal to numeric to be able to run correlations 
data = data.replace('No',0)
data = data.replace('NO',0)
data = data.replace('Yes',1)

In [72]:
data.dtypes
data.corr()

,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,citoglipton,diabetesMed
patient_nbr,1.000000,-0.011128,-0.136814,-0.032568,-0.024092,0.015946,-0.015570,0.020665,0.103379,0.062352,0.012480,0.226847,NaN,NaN,0.017232
admission_type_id,-0.011128,1.000000,0.083483,0.106654,-0.012500,-0.143713,0.129888,0.079535,0.026511,-0.019116,-0.038161,-0.117126,NaN,NaN,-0.000310
discharge_disposition_id,-0.136814,0.083483,1.000000,0.018193,0.162748,0.023415,0.015921,0.108753,-0.008715,-0.024471,0.020787,0.046891,NaN,NaN,-0.028887
admission_source_id,-0.032568,0.106654,0.018193,1.000000,-0.006965,0.048885,-0.135400,-0.054533,0.027244,0.059892,0.036314,0.072114,NaN,NaN,0.001500
time_in_hospital,-0.024092,-0.012500,0.162748,-0.006965,1.000000,0.318450,0.191472,0.466135,-0.008916,-0.009681,0.073623,0.220186,NaN,NaN,0.062520
num_lab_procedures,0.015946,-0.143713,0.023415,0.048885,0.318450,1.000000,0.058066,0.268161,-0.007602,-0.002279,0.039231,0.152773,NaN,NaN,0.033107
num_procedures,-0.015570,0.129888,0.015921,-0.135400,0.191472,0.058066,1.000000,0.385767,-0.024819,-0.038179,-0.066236,0.073734,NaN,NaN,-0.006821
num_medications,0.020665,0.079535,0.108753,-0.054533,0.466135,0.268161,0.385767,1.000000,0.045197,0.013180,0.064194,0.261526,NaN,NaN,0.186910
number_outpatient,0.103379,0.026511,-0.008715,0.027244,-0.008916,-0.007602,-0.024819,0.045197,1.000000,0.091459,0.107338,0.094152,NaN,NaN,0.016456
number_emergency,0.062352,-0.019116,-0.024471,0.059892,-0.009681,-0.002279,-0.038179,0.013180,0.091459,1.000000,0.266559,0.055539,NaN,NaN,0.025923
number_inpatient,0.012480,-0.038161,0.020787,0.036314,0.073623,0.039231,-0.066236,0.064194,0.107338,0.266559,1.000000,0.104710,NaN,NaN,0.026001
number_diagnoses,0.226847,-0.117126,0.046891,0.072114,0.220186,0.152773,0.073734,0.261526,0.094152,0.055539,0.104710,1.000000,NaN,NaN,0.021186
examide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citoglipton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diabetesMed,0.017232,-0.000310,-0.028887,0.001500,0.062520,0.033107,-0.006821,0.186910,0.016456,0.025923,0.026001,0.021186,NaN,NaN,1.000000

In [73]:
#convert objects to integer
data["diabetesMed"]=data["diabetesMed"].astype(int)

In [74]:
data.corr()

,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,examide,citoglipton,diabetesMed
patient_nbr,1.000000,-0.011128,-0.136814,-0.032568,-0.024092,0.015946,-0.015570,0.020665,0.103379,0.062352,0.012480,0.226847,NaN,NaN,0.017232
admission_type_id,-0.011128,1.000000,0.083483,0.106654,-0.012500,-0.143713,0.129888,0.079535,0.026511,-0.019116,-0.038161,-0.117126,NaN,NaN,-0.000310
discharge_disposition_id,-0.136814,0.083483,1.000000,0.018193,0.162748,0.023415,0.015921,0.108753,-0.008715,-0.024471,0.020787,0.046891,NaN,NaN,-0.028887
admission_source_id,-0.032568,0.106654,0.018193,1.000000,-0.006965,0.048885,-0.135400,-0.054533,0.027244,0.059892,0.036314,0.072114,NaN,NaN,0.001500
time_in_hospital,-0.024092,-0.012500,0.162748,-0.006965,1.000000,0.318450,0.191472,0.466135,-0.008916,-0.009681,0.073623,0.220186,NaN,NaN,0.062520
num_lab_procedures,0.015946,-0.143713,0.023415,0.048885,0.318450,1.000000,0.058066,0.268161,-0.007602,-0.002279,0.039231,0.152773,NaN,NaN,0.033107
num_procedures,-0.015570,0.129888,0.015921,-0.135400,0.191472,0.058066,1.000000,0.385767,-0.024819,-0.038179,-0.066236,0.073734,NaN,NaN,-0.006821
num_medications,0.020665,0.079535,0.108753,-0.054533,0.466135,0.268161,0.385767,1.000000,0.045197,0.013180,0.064194,0.261526,NaN,NaN,0.186910
number_outpatient,0.103379,0.026511,-0.008715,0.027244,-0.008916,-0.007602,-0.024819,0.045197,1.000000,0.091459,0.107338,0.094152,NaN,NaN,0.016456
number_emergency,0.062352,-0.019116,-0.024471,0.059892,-0.009681,-0.002279,-0.038179,0.013180,0.091459,1.000000,0.266559,0.055539,NaN,NaN,0.025923
number_inpatient,0.012480,-0.038161,0.020787,0.036314,0.073623,0.039231,-0.066236,0.064194,0.107338,0.266559,1.000000,0.104710,NaN,NaN,0.026001
number_diagnoses,0.226847,-0.117126,0.046891,0.072114,0.220186,0.152773,0.073734,0.261526,0.094152,0.055539,0.104710,1.000000,NaN,NaN,0.021186
examide,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
citoglipton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diabetesMed,0.017232,-0.000310,-0.028887,0.001500,0.062520,0.033107,-0.006821,0.186910,0.016456,0.025923,0.026001,0.021186,NaN,NaN,1.000000

In [1]:
data.dropna(subset=["payer_code"], axis = 0 , inplace= True)
data["payer_code"]
pd.unique(data['payer_code'])

NameError: name 'data' is not defined

In [84]:
print(data.isnull().sum())

patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
max_glu_serum               0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
examide                     0
citoglipton                 0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
glimepiride-pioglitazone    0
metformin-rosiglitazone     0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64